### ISSUE TITLE
All buildpack registry references should be updated from GCR to Dockerhub

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/samples#87]
## What happened?
We've recently started publishing all Paketo Buildpac artifacts to Dockerhub in addition to GCR. We should update all existing documentation to reference the Dockerhub locations so that we can eventually move over to Dockerhub completely.

**Comment by andymoe** [comment]
Dockerhub account is here: https://hub.docker.com/u/paketobuildpacks

**Comment by ryanmoran** [comment]
The registry entries already reference the DockerHub locations. For example, here are the entries for the Ruby buildpack: https://github.com/buildpacks/registry-index/blob/main/ru/by/paketo-buildpacks_ruby. Instead of referencing the buildpack locations at a specific registry like DockerHub or GCR, we should update the references in our sample READMEs to use the registry names.

As an example, the Ruby Puma example current specifies to run this command:
```
pack build puma-sample --buildpack gcr.io/paketo-buildpacks/ruby
```

That should be updated to the following:
```
pack build puma-sample --buildpack paketo-buildpacks/ruby
```
